In [69]:
import pandas as pd
rt_df = pd.read_csv("C:/Users/benedek/OneDrive - Central European University (CEU GmbH Hungarian Branch Office)/Liza Drini fájljai - DSP Group C/AggregatedData_AustralianSpeciesOccurrence.csv")

In [70]:
rt_df[3226173:].head()

,year,basisOfRecord,stateTerritory,ibraRegion,imcraRegion,forest2018Status,forest2013Status,capadStatus,epbcStatus,griisStatus,speciesID,speciesName,occurrenceCount
3226173,1985,PRESERVED_SPECIMEN,Northern Territory,Finke,NaN,non-forest,non-forest,not protected,Not listed,Native,https://biodiversity.org.au/afd/taxa/562f384e-...,Delma nasuta,2
3226174,1985,PRESERVED_SPECIMEN,Northern Territory,Finke,NaN,non-forest,non-forest,not protected,Not listed,Native,https://biodiversity.org.au/afd/taxa/5815e99d-...,Lophochroa leadbeateri,1
3226175,1985,PRESERVED_SPECIMEN,Northern Territory,Finke,NaN,non-forest,non-forest,not protected,Not listed,Native,https://biodiversity.org.au/afd/taxa/5d73fc2f-...,Pseudomys hermannsburgensis,5
3226176,1985,PRESERVED_SPECIMEN,Northern Territory,Finke,NaN,non-forest,non-forest,not protected,Not listed,Native,https://biodiversity.org.au/afd/taxa/5fed5ecf-...,Barnardius zonarius,1
3226177,1985,PRESERVED_SPECIMEN,Northern Territory,Finke,NaN,non-forest,non-forest,not protected,Not listed,Native,https://biodiversity.org.au/afd/taxa/60914d7f-...,Delma butleri,2

In [71]:
rt_df.dtypes

year                 int64
basisOfRecord       object
stateTerritory      object
ibraRegion          object
imcraRegion         object
forest2018Status    object
forest2013Status    object
capadStatus         object
epbcStatus          object
griisStatus         object
speciesID           object
speciesName         object
occurrenceCount      int64
dtype: object

In [72]:
cat_fix = ['']

In [73]:
numerical_fix = ['year', 'occurrenceCount']
rt_df[numerical_fix] = rt_df[numerical_fix].apply(pd.to_numeric, errors='coerce')

In [74]:
cat_df = rt_df[rt_df['speciesName'] == 'Felis catus']

In [75]:
cat_df.head()

,year,basisOfRecord,stateTerritory,ibraRegion,imcraRegion,forest2018Status,forest2013Status,capadStatus,epbcStatus,griisStatus,speciesID,speciesName,occurrenceCount
2902,1900,HUMAN_OBSERVATION,New South Wales,South Eastern Highlands,NaN,forest,non-forest,not protected,Not listed,Invasive,https://biodiversity.org.au/afd/taxa/7de6b16a-...,Felis catus,1
5093,1900,HUMAN_OBSERVATION,South Australia,Eyre Yorke Block,NaN,non-forest,non-forest,PA,Not listed,Invasive,https://biodiversity.org.au/afd/taxa/7de6b16a-...,Felis catus,3
5592,1900,HUMAN_OBSERVATION,South Australia,Kanmantoo,NaN,non-forest,non-forest,PA,Not listed,Invasive,https://biodiversity.org.au/afd/taxa/7de6b16a-...,Felis catus,1
33768,1903,HUMAN_OBSERVATION,Queensland,Brigalow Belt South,NaN,non-forest,non-forest,not protected,Not listed,Invasive,https://biodiversity.org.au/afd/taxa/7de6b16a-...,Felis catus,1
114291,1911,HUMAN_OBSERVATION,New South Wales,NSW North Coast,NaN,non-forest,non-forest,PA,Not listed,Invasive,https://biodiversity.org.au/afd/taxa/7de6b16a-...,Felis catus,2

In [76]:
cat_df = cat_df.drop(columns = ['griisStatus', 'epbcStatus', 'speciesID', 'basisOfRecord', 'imcraRegion'])

In [77]:
cat_df = cat_df[rt_df['year'] > 1959]

C:\Users\benedek\AppData\Local\Temp\ipykernel_5436\355998430.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cat_df = cat_df[rt_df['year'] > 1959]

## Cleaning dataset

In [78]:
cat_df

,year,stateTerritory,ibraRegion,forest2018Status,forest2013Status,capadStatus,speciesName,occurrenceCount
827338,1960,New South Wales,South East Corner,forest,forest,not protected,Felis catus,3
827397,1960,New South Wales,South Eastern Highlands,forest,non-forest,not protected,Felis catus,1
827587,1960,New South Wales,South Eastern Queensland,forest,forest,not protected,Felis catus,1
838813,1960,Australian Capital Territory,South Eastern Highlands,non-forest,non-forest,not protected,Felis catus,1
885133,1961,Northern Territory,Daly Basin,forest,non-forest,not protected,Felis catus,1
...,...,...,...,...,...,...,...,...
11617331,2022,NaN,NaN,non-forest,non-forest,not protected,Felis catus,2
11617334,2022,NaN,NaN,non-forest,non-forest,PA,Felis catus,4
11617335,2022,NaN,NaN,non-forest,non-forest,not protected,Felis catus,2
11617336,2022,NaN,NaN,non-forest,non-forest,PA,Felis catus,5
11617339,2022,NaN,NaN,non-forest,non-forest,not protected,Felis catus,2

In [79]:
cat_df.head()

,year,stateTerritory,ibraRegion,forest2018Status,forest2013Status,capadStatus,speciesName,occurrenceCount
827338,1960,New South Wales,South East Corner,forest,forest,not protected,Felis catus,3
827397,1960,New South Wales,South Eastern Highlands,forest,non-forest,not protected,Felis catus,1
827587,1960,New South Wales,South Eastern Queensland,forest,forest,not protected,Felis catus,1
838813,1960,Australian Capital Territory,South Eastern Highlands,non-forest,non-forest,not protected,Felis catus,1
885133,1961,Northern Territory,Daly Basin,forest,non-forest,not protected,Felis catus,1

In [80]:
cat_df.dtypes

year                 int64
stateTerritory      object
ibraRegion          object
forest2018Status    object
forest2013Status    object
capadStatus         object
speciesName         object
occurrenceCount      int64
dtype: object

In [81]:
#to drop: griisStatuts, epbcStatus, speciesID, basisOfRecord, imcraRegion 'Unnamed: 0',

In [82]:
cat_df

,year,stateTerritory,ibraRegion,forest2018Status,forest2013Status,capadStatus,speciesName,occurrenceCount
827338,1960,New South Wales,South East Corner,forest,forest,not protected,Felis catus,3
827397,1960,New South Wales,South Eastern Highlands,forest,non-forest,not protected,Felis catus,1
827587,1960,New South Wales,South Eastern Queensland,forest,forest,not protected,Felis catus,1
838813,1960,Australian Capital Territory,South Eastern Highlands,non-forest,non-forest,not protected,Felis catus,1
885133,1961,Northern Territory,Daly Basin,forest,non-forest,not protected,Felis catus,1
...,...,...,...,...,...,...,...,...
11617331,2022,NaN,NaN,non-forest,non-forest,not protected,Felis catus,2
11617334,2022,NaN,NaN,non-forest,non-forest,PA,Felis catus,4
11617335,2022,NaN,NaN,non-forest,non-forest,not protected,Felis catus,2
11617336,2022,NaN,NaN,non-forest,non-forest,PA,Felis catus,5
11617339,2022,NaN,NaN,non-forest,non-forest,not protected,Felis catus,2

In [83]:
cat_df.isna().sum()
cat_df = cat_df.dropna()

In [84]:
cat_df

,year,stateTerritory,ibraRegion,forest2018Status,forest2013Status,capadStatus,speciesName,occurrenceCount
827338,1960,New South Wales,South East Corner,forest,forest,not protected,Felis catus,3
827397,1960,New South Wales,South Eastern Highlands,forest,non-forest,not protected,Felis catus,1
827587,1960,New South Wales,South Eastern Queensland,forest,forest,not protected,Felis catus,1
838813,1960,Australian Capital Territory,South Eastern Highlands,non-forest,non-forest,not protected,Felis catus,1
885133,1961,Northern Territory,Daly Basin,forest,non-forest,not protected,Felis catus,1
...,...,...,...,...,...,...,...,...
11617293,2022,Western Australia,Swan Coastal Plain,non-forest,non-forest,PA,Felis catus,1
11617298,2022,Western Australia,Swan Coastal Plain,non-forest,non-forest,not protected,Felis catus,5
11617302,2022,Western Australia,Warren,forest,forest,PA,Felis catus,1
11617306,2022,Western Australia,Warren,non-forest,non-forest,PA,Felis catus,1
11617308,2022,Western Australia,Yalgoo,non-forest,non-forest,not protected,Felis catus,2

In [85]:
cat_df.isna().sum()

year                0
stateTerritory      0
ibraRegion          0
forest2018Status    0
forest2013Status    0
capadStatus         0
speciesName         0
occurrenceCount     0
dtype: int64

In [86]:
cat_df.to_csv("Cat_only_rt.csv", index=False)

In [87]:
r = pd.read_csv("../datasets/Cat_only_rt.csv")
r

,year,stateTerritory,ibraRegion,forest2018Status,forest2013Status,capadStatus,speciesName,occurrenceCount
0,1960,New South Wales,South East Corner,forest,forest,not protected,Felis catus,3
1,1960,New South Wales,South Eastern Highlands,forest,non-forest,not protected,Felis catus,1
2,1960,New South Wales,South Eastern Queensland,forest,forest,not protected,Felis catus,1
3,1960,Australian Capital Territory,South Eastern Highlands,non-forest,non-forest,not protected,Felis catus,1
4,1961,Northern Territory,Daly Basin,forest,non-forest,not protected,Felis catus,1
...,...,...,...,...,...,...,...,...
4944,2022,Western Australia,Swan Coastal Plain,non-forest,non-forest,PA,Felis catus,1
4945,2022,Western Australia,Swan Coastal Plain,non-forest,non-forest,not protected,Felis catus,5
4946,2022,Western Australia,Warren,forest,forest,PA,Felis catus,1
4947,2022,Western Australia,Warren,non-forest,non-forest,PA,Felis catus,1
4948,2022,Western Australia,Yalgoo,non-forest,non-forest,not protected,Felis catus,2

## Analysis

### Linear regression on sheep and cats

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [17]:
df = pd.read_csv("../datasets/farm_cat.csv")
df = df[df["territory"] == "All Australia"] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

# df = df[~df["territory"].str.contains("All Australia", case=False, na=False)]

In [31]:
df_reg = df[["sheep_flock", "cats_occurrence_total"]].copy()

imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed

     sheep_flock  cats_occurrence_total
0        17123.0              69.000000
1            4.0              43.000000
2        17443.0              17.000000
3        10952.0              26.000000
4         2589.0             117.465608
..           ...                    ...
226       3706.0              78.000000
227       8842.0             150.000000
228       1795.0             118.000000
229       4239.0             183.000000
230       5482.0              60.000000

[231 rows x 2 columns]

In [33]:
X = df_reg_imputed[["cats_occurrence_total"]]
y = df_reg_imputed["sheep_flock"]

In [34]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

  Coefficient: 3.7055
  R²         : 0.0187
  RMSE       : 4,730.34

### Linear regression with more variables

In [ ]:
df = pd.read_csv("../datasets/farm_cat.csv")
df = df[~df["territory"].str.contains("All Australia", case=False, na=False)] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

df_reg = df[["sheep_flock", "cats_occurrence_total", "year"]].copy()


imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed["territory"] = df["territory"]
df_encoded = pd.get_dummies(df_reg_imputed, columns=['territory'], drop_first=True)

X = df_encoded.drop(columns=["sheep_flock"])
y = df_encoded["sheep_flock"]

In [36]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

  Coefficient: 7.6384
  R²         : 0.1912
  RMSE       : 4,294.53

In [38]:
df = pd.read_csv("../datasets/farm_cat.csv")
# df = df[~df["territory"].str.contains("All Australia", case=False, na=False)] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

df_reg = df[["sheep_flock", "cats_occurrence_total", "year"]].copy()


imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed["territory"] = df["territory"]
df_encoded = pd.get_dummies(df_reg_imputed, columns=['territory'], drop_first=True)

X = df_encoded.drop(columns=["sheep_flock"])
y = df_encoded["sheep_flock"]

In [39]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

  Coefficient: -5.7541
  R²         : 0.9251
  RMSE       : 3,887.19

In [13]:
df = pd.read_csv("../datasets/farm_cat.csv")
df = df[df["territory"] == "All Australia"] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

df_reg = df[["sheep_purchased", "cats_occurrence_total", "year"]].copy()


imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed["territory"] = df["territory"]
df_encoded = pd.get_dummies(df_reg_imputed, columns=['territory'], drop_first=True)

X = df_encoded.drop(columns=["sheep_purchased"])
y = df_encoded["sheep_purchased"]

In [14]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

  Coefficient: -0.0585
  R²         : 0.8076
  RMSE       : 549.30

In [21]:
df = pd.read_csv("../datasets/farm_cat.csv")
df = df[df["territory"] == "New South Wales"] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

df_reg = df[["sheep_flock", "cats_occurrence_total", "year"]].copy()


imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed["territory"] = df["territory"]
df_encoded = pd.get_dummies(df_reg_imputed, columns=['territory'], drop_first=True)

X = df_encoded.drop(columns=["sheep_flock"])
y = df_encoded["sheep_flock"]

In [28]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("Intercept:", model.intercept_)
print(coef_df)
print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

Intercept: 439225.04452959396
                 Feature  Coefficient
0  cats_occurrence_total     2.216945
1                   year  -213.933342
  Coefficient: 2.2169
  R²         : 0.6314
  RMSE       : 1,220.71

In [29]:
df = pd.read_csv("../datasets/farm_cat.csv")
df = df[df["territory"] == "Western Australia"] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

df_reg = df[["sheep_flock", "cats_occurrence_total", "year"]].copy()


imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed["territory"] = df["territory"]
df_encoded = pd.get_dummies(df_reg_imputed, columns=['territory'], drop_first=True)

X = df_encoded.drop(columns=["sheep_flock"])
y = df_encoded["sheep_flock"]

In [30]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("Intercept:", model.intercept_)
print(coef_df)
print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

Intercept: 873428.7527866664
                 Feature  Coefficient
0  cats_occurrence_total    26.041135
1                   year  -430.361646
  Coefficient: 26.0411
  R²         : 0.8938
  RMSE       : 1,392.71

In [31]:
df = pd.read_csv("../datasets/farm_cat.csv")
df = df[df["territory"] == "Tasmania"] # this line destroys our analysis, it went from R2 = 0.925 to 0.191

df_reg = df[["sheep_flock", "cats_occurrence_total", "year"]].copy()


imputer = SimpleImputer(strategy="mean")
df_reg_imputed = pd.DataFrame(imputer.fit_transform(df_reg), columns=df_reg.columns)
df_reg_imputed["territory"] = df["territory"]
df_encoded = pd.get_dummies(df_reg_imputed, columns=['territory'], drop_first=True)

X = df_encoded.drop(columns=["sheep_flock"])
y = df_encoded["sheep_flock"]

In [32]:
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2   = r2_score(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("Intercept:", model.intercept_)
print(coef_df)
print(f"  Coefficient: {model.coef_[0]:,.4f}")
print(f"  R²         : {r2:.4f}")
print(f"  RMSE       : {rmse:,.2f}")

Intercept: 50633.74994815513
                 Feature  Coefficient
0  cats_occurrence_total     0.533081
1                   year   -24.201185
  Coefficient: 0.5331
  R²         : 0.5070
  RMSE       : 225.77

In [ ]:
# code for stat analysis of each region change code to fit ur own df

import statsmodels.api as sm

for state in merged['territory'].unique():
    state_df = merged[merged['territory'] == state]

    X = sm.add_constant(state_df['sheep_flock'])
    y = state_df['cats_nonforest']

    model = sm.OLS(y, X).fit()
    print(f"\n{state}")
    print(model.summary())
# if p value less than 0.05 signif